from __future__ import annotations

GRAY_18 = '#767676'
GRAY_0 = '#000000'
GRAY_1 = '#101010'
GRAY_2 = '#1a1a1a'
GRAY_3 = '#262626'
GRAY_4 = '#404040'

ACCENT_COLOR_TEXT = '#ee9470'
ACCENT_COLOR_TEXT_SECONDARY = '#63c3cf'
TEXT_DIM = '#8d8d8d'
TEXT_MAIN = '#cecece'
TEXT_HI = '#f2f2f2'

FONT_WEIGHT_SEMIBOLD = 600
FONT_WEIGHT_BOLD = 700

# Layout rhythm
SIZE_TAB_STRIP_OFFSET = '0px'
SIZE_TAB_MARGIN_RIGHT = '4px'
SIZE_FORM_SPACING = '4px'
SIZE_CHECKBOX_SPACING = '6px'
SIZE_SPLITTER_HANDLE_WIDTH = '1px'
SIZE_SPLITTER_HANDLE_MARGIN_LEFT = '8px'
SIZE_SECTION_STACK_SPACING = '6px'

# Inline paddings
# NAT 2026-07-22: more breathing room on the sides of button text.
SIZE_CONTROL_PADDING = '2px 8px'
SIZE_BUTTON_PADDING = '0px 12px'
SIZE_HEADER_PADDING = '2px 6px'
SIZE_TAB_PADDING = '4px 8px'
SIZE_TOOLBUTTON_PADDING = '2px 4px'
SIZE_TOOLBUTTON_POPUP_PADDING_RIGHT = '2px'

# Heights and widths
SIZE_CONTROL_MIN_HEIGHT = '18px'
SIZE_COMPACT_BUTTON_MIN_HEIGHT = '20px'
SIZE_BUTTON_MIN_HEIGHT = '30px'
SIZE_FOOTER_MIN_HEIGHT = SIZE_BUTTON_MIN_HEIGHT
SIZE_SPIN_BUTTON_WIDTH = '12px'
SIZE_COMBO_DROPDOWN_WIDTH = '14px'
SIZE_CHECKBOX_INDICATOR = '14px'
SIZE_SCROLLBAR_HANDLE_MIN = '24px'

# Runtime layout metrics
SIZE_APP_MARGIN = 6
SIZE_PANEL_MARGIN = 10
SIZE_TAB_CONTENT_TOP_MARGIN = 20
# NAT 2026-07-22 'match padding overall': card interiors are UNIFORM —
# the old 24px left indent vs 8px right read as mismatched padding.
SIZE_SECTION_FRAME_MARGIN = 12
SIZE_SECTION_FRAME_INDENT = 12
SIZE_FOOTER_ITEM_SPACING = 4
SIZE_FOOTER_TOP_SPACING = 8
SIZE_FOOTER_BOTTOM_INSET = 6

# Phase 15C (v1.0.0): the layered grey ramp — window < card < control <
# hover, Mac-style depth. The CANVAS surround swatches (napari_layout
# CANVAS_BACKGROUND_OPTIONS incl. GRAY_18) are PHOTOGRAPHIC references and
# deliberately NOT part of this ramp.
WINDOW_BG = '#161616'
CARD_BG = '#1d1d1d'
RAMP_CONTROL = '#262626'
RAMP_HOVER = '#303030'

# Phase 15C radius tokens — one consistent rounding language.
RADIUS_CARD = '8px'
RADIUS_CONTROL = '5px'

# Widget color definitions
BASE_BG = WINDOW_BG
PANEL_BG = WINDOW_BG
PANEL_BG_ACTIVE = CARD_BG
TAB_SELECTED_BG = WINDOW_BG
TAB_TEXT_ACCENT = ACCENT_COLOR_TEXT
CONTROL_BG = RAMP_CONTROL
CONTROL_BG_HOVER = RAMP_HOVER
CONTROL_BG_PRESSED = CARD_BG
CONTROL_MENU_BG = CARD_BG
CONTROL_SELECTION_BG = RAMP_HOVER
TEXT_SELECTION_BG = GRAY_4
HEADER_BG = CARD_BG
CHECKED_BG = RAMP_HOVER
DISABLED_BG = '#1b1b1b'
SCROLLBAR_HANDLE_BG = GRAY_2
SPLITTER_BG = GRAY_1
STATUS_BG = GRAY_2
BUTTON_ACCENT_BG = GRAY_1
BUTTON_ACCENT_BG_HOVER = GRAY_2
BUTTON_ACCENT_BG_PRESSED = GRAY_1
TEXT_PRIMARY = TEXT_MAIN
TEXT_SOFT = TEXT_DIM
TEXT_BRIGHT = TEXT_HI
TEXT_HEADER = TEXT_MAIN
TEXT_CONTROL = TEXT_MAIN
TEXT_HEADER_SECTION = TEXT_DIM
TEXT_ACCENT = ACCENT_COLOR_TEXT
TEXT_STATUS = TEXT_MAIN
HEADER_DIVIDER_LINE = GRAY_1
BOOL_EDITOR_HOVER_BG = GRAY_2
BOOL_EDITOR_FILL_ENABLED = GRAY_1
BOOL_EDITOR_FILL_DISABLED = GRAY_1
BOOL_EDITOR_CHECKED_ENABLED = GRAY_1
BOOL_EDITOR_CHECKED_DISABLED = GRAY_1
BOOL_EDITOR_BORDER_CHECKED = GRAY_0
BOOL_EDITOR_BORDER_UNCHECKED = GRAY_0
BOOL_EDITOR_CHECKMARK = TEXT_MAIN