"""Chinese help text for controls, keyed by stable parameter paths."""

from __future__ import annotations


PARAM_TOOLTIPS = {
    'film_render.dir_couplers.active': '启用 DIR 耦合剂的抑制效果。',
    'film_render.dir_couplers.amount': 'DIR 抑制矩阵的整体倍率。1.0 保持各通道原有伽马值。',
    'film_render.dir_couplers.inhibition_samelayer': '同层抑制倍率；控制各 RGB 层内部的对比度和伽马降低程度。',
    'film_render.dir_couplers.inhibition_interlayer': '层间抑制倍率；控制 DIR 层间作用带来的饱和度增强。',
    'film_render.dir_couplers.gamma_samelayer_rgb': '红、绿、蓝各层的同层 DIR 伽马；决定各层密度曲线的伽马降低量。',
    'film_render.dir_couplers.gamma_interlayer_r_to_gb': '红层分别对绿层和蓝层的 DIR 抑制量。',
    'film_render.dir_couplers.gamma_interlayer_g_to_rb': '绿层分别对红层和蓝层的 DIR 抑制量。',
    'film_render.dir_couplers.gamma_interlayer_b_to_rg': '蓝层分别对红层和绿层的 DIR 抑制量。',
    'film_render.dir_couplers.diffusion_size_um': '耦合剂扩散范围的标准差，单位 μm；典型值 5–20 μm，会影响锐度和饱和度。',
    'film_render.halation.active': '启用光晕和乳剂内部散射。',
    'film_render.halation.scatter_amount': '散射整体强度。1.0 为完整物理散射，0.0 为无散射。',
    'film_render.halation.scatter_spatial_scale': '散射范围倍率；同时缩放核心和拖尾的范围。1.0 为物理默认值。',
    'film_render.halation.halation_amount': '光晕整体强度倍率；缩放各通道的光晕振幅。1.0 为物理默认值。',
    'film_render.halation.halation_spatial_scale': '光晕范围倍率；缩放首次反射的扩散范围。1.0 为物理默认值。',
    'film_render.halation.boost_ev': '高光增强的最大档数（EV）。',
    'film_render.halation.protect_ev': '从中灰开始计算，高光增强启动前受保护的曝光范围（EV）。',
    'film_render.halation.boost_range': '控制高光增强从 0 到 1 增长的速度。',
    'film_render.halation.scatter_core_um': '各通道散射核心的高斯标准差，单位 μm；影响乳剂中的细节锐度。',
    'film_render.halation.scatter_tail_um': '各通道散射拖尾的衰减范围，单位 μm；控制乳剂内部较远距离的微弱扩散。',
    'film_render.halation.scatter_tail_weight': '各通道散射拖尾的权重（0–1）。数值越大，扩散到远处的光越多。',
    'film_render.halation.halation_strength': '各通道背面反射光晕的总振幅（0–1）；蓝色通道通常接近零。',
    'film_render.halation.halation_first_sigma_um': '各通道首次反射光晕的标准差，单位 μm；与片基厚度有关。',
    'film_render.halation.halation_n_bounces': '光晕计算中叠加的反射次数；典型值为 2–3 次。',
    'film_render.halation.halation_bounce_decay': '每次反射后的振幅衰减比例；物理范围约 0.3–0.7。',
    'film_render.halation.halation_renormalize': '启用后重新归一化光晕能量，以保持中灰亮度；关闭时光晕会额外抬高暗部。',
    'film_render.grain.active': '为胶片负片添加颗粒。',
    'film_render.grain.sublayers_active': '启用各乳剂子层的独立颗粒结构。',
    'film_render.grain.particle_area_um2': '颗粒面积，单位 μm²；与感光度有关，例如 ISO 400 常用约 0.4。',
    'film_render.grain.particle_scale': '红、绿、蓝各层颗粒面积的倍率。',
    'film_render.grain.particle_scale_layers': '每个颜色层中各子层颗粒面积的倍率。',
    'film_render.grain.density_min': '颗粒的最低密度；典型值约 0.03–0.06。',
    'film_render.grain.uniformity': '颗粒均匀度；典型值约 0.94–0.98。',
    'film_render.grain.blur': '颗粒高斯模糊的标准差，单位像素；大倍率时可提高至约 0.8–0.9。',
    'film_render.grain.blur_dye_clouds_um': '染料云高斯模糊范围的倍率；用于高倍率观察。1 为默认值。',
    'film_render.grain.micro_structure': '极高倍率下的分子团微观结构参数：模糊尺度（μm）和分子团尺寸（nm）。',
    'print_render.glare.active': '为相纸添加眩光。',
    'print_render.glare.percent': '参与眩光的光量比例；典型值约 0.1–0.25。',
    'print_render.glare.roughness': '眩光的粗糙程度（0–1）。',
    'print_render.glare.blur': '眩光高斯模糊的标准差，单位像素。',
    'print_render.density_curves_morph.active': '启用相纸密度曲线形变。',
    'print_render.density_curves_morph.gamma_factor': '相纸各密度曲线共同使用的伽马倍率。',
    'print_render.density_curves_morph.gamma_factor_fast': '快感光子层的伽马倍率。',
    'print_render.density_curves_morph.gamma_factor_slow': '中、慢感光子层的伽马倍率。',
    'print_render.density_curves_morph.gamma_factor_red': '红色通道的伽马倍率。',
    'print_render.density_curves_morph.gamma_factor_green': '绿色通道的伽马倍率。',
    'print_render.density_curves_morph.gamma_factor_blue': '蓝色通道的伽马倍率。',
    'print_render.density_curves_morph.developer_exhaustion': '将相纸三个子层的肩部曲线向匹配的 Gumbel 曲线过渡，同时保持中灰。',
    'enlarger.preflash_exposure': '相纸预闪光的曝光量，单位 EV。',
    'enlarger.preflash_y_filter_shift': '预闪光时黄色滤镜相对中性位置的偏移，单位为 Kodak CC。',
    'enlarger.preflash_m_filter_shift': '预闪光时洋红滤镜相对中性位置的偏移，单位为 Kodak CC。',
    'camera.film_format_mm': '胶片画幅长边尺寸，单位 mm，例如 8、16、35、60 或 120。',
    'camera.lens_blur_um': '相机镜头模糊的高斯标准差，单位 μm；普通镜头约 5 μm，优质镜头约 2–4 μm。',
    'camera.auto_exposure_method': '虚拟相机自动曝光所用的测光方式。',
    'camera.auto_exposure': '启用虚拟相机的自动曝光。',
    'camera.exposure_compensation_ev': '调整相机自动曝光的偏移量，单位 EV。',
    'scanner.lens_blur': '扫描仪镜头模糊的高斯标准差，单位像素。',
    'scanner.white_correction': '启用扫描结果的白点校正。',
    'scanner.white_level': '启用白点校正时使用的目标白电平。',
    'scanner.black_correction': '启用扫描结果的黑点校正。',
    'scanner.black_level': '启用黑点校正时使用的目标黑电平。',
    'scanner.unsharp_mask': '扫描结果的锐化蒙版参数：[标准差（像素），强度]。',
    'io.input_gamut_compress.active': '在光谱重建前，将输入色度压缩到可见光谱轨迹附近；关闭时保持原值。',
    'io.input_gamut_compress.algorithm': 'xy：在 CIE 1931 色度图中径向压缩；oklch：保持明度和色相，降低感知色度。',
    'io.input_gamut_compress.knee': 'Reinhard 压缩曲线参数：[阈值、上限、幂次]；默认值使色度平滑靠近光谱边界。',
    'io.output_gamut_compress.algorithm': '输出色域压缩算法。关闭可保留原值；CAM16-UCS 为默认算法，其他选项包括 Oklch、ACES RGC 等。',
    'io.output_gamut_compress.knee': '输出色度的 Reinhard 压缩曲线参数：[阈值、上限、幂次]。',
    'io.input_color_space': '输入图像的色彩空间；内部会转换为 sRGB，并裁剪负值。',
    'io.input_cctf_decoding': '对输入色彩空间应用逆 CCTF 传递函数。',
    'io.upscale_factor': '放大图像尺寸，以提高输出分辨率。',
    'io.crop': '按原图比例裁剪，用于按实际尺寸预览细节。',
    'io.crop_center': '裁剪区域中心的相对坐标 [x, y]，范围 0–1。',
    'io.crop_size': '裁剪区域相对长边的归一化尺寸 [x, y]，范围 0–1。',
    'settings.rgb_to_raw_method': '图像的光谱重建方法；Hanatos2025 支持完整可见范围，Mallett2019 仅支持 sRGB。',
    'settings.apply_hanatos2025_adaptation_window': '重建光谱时应用 Hanatos2025 带通适应窗口。',
    'settings.apply_hanatos2025_adaptation_surface': '重建光谱时应用 Hanatos2025 表面适应多项式。',
    'settings.spectral_gaussian_blur': '重建光谱上的高斯模糊标准差，单位 nm。',
    'film_render.density_curve_gamma': '负片密度曲线的伽马系数：小于 1 降低对比度，大于 1 提高对比度。',
    'use_display_transform': '在 Windows 上读取显示器配置文件并转换预览颜色；关闭后直接使用输出色彩空间。',
    'gray_18_canvas': '使用中性 18% 灰色背景，方便判断曝光和色彩中性。',
    'white_padding': '在预览图像周围增加白边，数值为相对图像长边的比例。',
    'settings.preview_max_size': '预览图像长边的最大像素数。',
    'output_interpolation': '预览窗口显示输出图层时使用的插值方式。',
    'selection.film_stock': '选择要模拟的胶片型号。',
    'selection.print_paper': '选择要模拟的相纸型号。',
    'enlarger.illuminant': '选择虚拟放大机的光源。',
    'enlarger.print_exposure_compensation': '根据相机曝光补偿自动调整相纸曝光。',
    'enlarger.print_exposure': '调整虚拟放大机的曝光时间。',
    'enlarger.y_filter_shift': '彩色放大机黄色滤镜相对中性位置的偏移，单位 Kodak CC。',
    'enlarger.m_filter_shift': '彩色放大机洋红滤镜相对中性位置的偏移，单位 Kodak CC。',
    'io.output_color_space': '模拟结果的输出色彩空间。',
    'workflow.saving_color_space': '保存图像文件时使用的色彩空间。',
    'workflow.saving_cctf_encoding': '保存图像文件时是否应用 CCTF 编码。',
    'workflow.auto_preview': '每次修改界面参数后自动更新预览；也可以用鼠标滚轮调整数值。',
    'io.scan_film': '显示负片扫描结果，而不是相纸打印结果。',
    'white_balance': '选择白平衡模式；自定义模式可调整色温和色调。',
    'temperature': '自定义白平衡的色温，单位 K；其他模式不使用此值。',
    'tint': '自定义白平衡的色调；其他模式不使用此值。',
    'lens_correction': '导入 RAW 时应用镜头校正。',
    'scan_for_print': '按相纸扫描：启用扫描仪黑白点校正，并关闭眩光。',
}

DIFFUSION_TOOLTIPS = {
    'active': '启用柔焦滤镜（Pro-Mist 系列）。',
    'filter_family': '选择点扩散函数类型。Black Pro-Mist 会吸收部分偏转光，其他类型大体保持能量。',
    'strength': '滤镜标称强度：0、1/8、1/4、1/2、1 或 2；内部换算为散射与吸收比例。',
    'spatial_scale': '图像平面上柔焦范围的倍率；可用于适配不同画幅和放大尺寸。',
    'halo_warmth': '晕光的暖调偏移。正值使外晕偏暖、内晕偏冷；0 使用滤镜默认值。',
    'core_intensity': '高级参数：核心权重倍率；1.0 为滤镜默认值。',
    'core_size': '高级参数：核心范围倍率；1.0 为滤镜默认值。',
    'halo_intensity': '高级参数：晕光权重倍率；1.0 为滤镜默认值。',
    'halo_size': '高级参数：晕光范围倍率；1.0 为滤镜默认值。',
    'bloom_intensity': '高级参数：泛光权重倍率；1.0 为滤镜默认值。',
    'bloom_size': '高级参数：泛光范围倍率；1.0 为滤镜默认值。',
}

BUTTON_TOOLTIPS = {
    'run the simulation on a small preview and deactivates grain, halation, blurs, unsharp mask (diffusion filters are active)': '快速预览：使用较小图像，并暂时关闭颗粒、光晕、模糊和锐化；柔焦滤镜仍生效。',
    'run the full simulation on the full-resolution input': '以原始分辨率运行完整模拟。',
    'save the current output layer to an image file': '将当前输出图层保存为图像文件。',
    'load and process a raw file using rawpy, output colorspace and cctf as defined in current input widget state': '使用当前输入设置导入并处理 RAW 文件。',
    'pixel of the screen mapped 1 to 1 to the image pixel': '屏幕像素与图像像素按 1:1 显示。',
    '2 screen pixels mapped to 1 image pixel': '每个图像像素使用 2 个屏幕像素显示。',
    '4 screen pixels mapped to 1 image pixel': '每个图像像素使用 4 个屏幕像素显示。',
}


def translate_param_tooltip(path: str, original: str) -> str:
    if '.diffusion_filter.' in path:
        return DIFFUSION_TOOLTIPS.get(path.rsplit('.', 1)[-1], original)
    return PARAM_TOOLTIPS.get(path, original)


def translate_button_tooltip(original: str) -> str:
    return BUTTON_TOOLTIPS.get(original.casefold(), original)
